[options]
addons_path = C:\Project\odoo19\odoo\addons,C:\Project\odoo19\POS_Restaurant
admin_passwd = admin123

db_host = localhost
db_port = 5432
db_user = odoo
db_password = 1234
db_name = pos

logfile = C:\Project\odoo19\POS_Restaurant\POS.log
http_port = 9981
proxy_mode = False

limit_memory_soft = 268435456
limit_memory_hard = 536870912
limit_time_cpu = 60
limit_time_real = 120
workers = 0



# python C:\Project\odoo19\odoo\odoo-bin -c odoo.conf

# python C:\Project\odoo19\odoo\odoo-bin -c odoo.conf -d POS_restaurant -i base